apiVersion: v1
kind: Service
metadata:
  name: user-service
  labels:
    app: tinyx
    component: user-service
spec:
  selector:
    app: tinyx
    component: user-service
  ports:
    - name: http
      port: 8080
      targetPort: 8080