apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  labels:
    app: tinyx
    component: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tinyx
      component: redis
  template:
    metadata:
      labels:
        app: tinyx
        component: redis
    spec:
      containers:
      - name: redis
        image: redis:7.0-alpine
        ports:
        - name: redis
          containerPort: 6379
        volumeMounts:
        - name: redis-data
          mountPath: /data
      volumes:
      - name: redis-data
        emptyDir: {}
