apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: tinyx
    component: redis
spec:
  selector:
    app: tinyx
    component: redis
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
      protocol: TCP