apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  labels:
    app: tinyx
    component: elasticsearch
spec:
  selector:
    app: tinyx
    component: elasticsearch
  ports:
    - name: http
      port: 9200
      targetPort: 9200
    - name: transport
      port: 9300
      targetPort: 9300
