apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elasticsearch
  labels:
    app: tinyx
    component: elasticsearch
spec:
  serviceName: elasticsearch
  replicas: 1
  selector:
    matchLabels:
      app: tinyx
      component: elasticsearch
  template:
    metadata:
      labels:
        app: tinyx
        component: elasticsearch
    spec:
      containers:
      - name: elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch:8.9.0
        ports:
        - name: http
          containerPort: 9200
        - name: transport
          containerPort: 9300
        env:
        - name: ES_JAVA_OPTS
          value: "-Xms512m -Xmx512m"
        - name: discovery.type
          value: single-node
        - name: xpack.security.enabled
          value: "false"
        - name: bootstrap.memory_lock
          value: "true"
        volumeMounts:
        - name: elasticsearch-data
          mountPath: /usr/share/elasticsearch/data
        - name: elasticsearch-init
          mountPath: /usr/share/elasticsearch/config/init.json
          subPath: init.json
      volumes:
      - name: elasticsearch-init
        configMap:
          name: elasticsearch-init
  volumeClaimTemplates:
  - metadata:
      name: elasticsearch-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 250Mi 
