apiVersion: apps/v1
kind: Deployment
metadata:
  name: timeline-user
  labels:
    app: tinyx
    component: timeline-user

spec:
  replicas: 1
  selector:
    matchLabels:
      app: tinyx
      component: timeline-user
  template:
    metadata:
      labels:
        app: tinyx
        component: timeline-user
    spec:
      imagePullSecrets:
        - name: tinyx-pull-secret
      containers:
        - name: timeline-user
          image: registry.cri.epita.fr/ing/majeures/tc/info/student/2026/2025-epitweet-tinyx-21/srvc-user-timeline
          ports:
            - name: http
              containerPort: 8084
          env:
            - name: QUARKUS_NEO4J_URI
              value: bolt://shared-neo4j.tinyx.svc.cluster.local:7687/social
            - name: QUARKUS_REDIS_HOSTS
              value: redis://redis.tinyx.svc.cluster.local:6379
            - name: QUARKUS_MONGODB_CONNECTION__STRING
              value: mongodb://admin:admin@shared-mongodb-0.shared-mongodb.tinyx.svc.cluster.local:27017/user_timelines_db?authSource=admin&retryWrites=true&w=majority&uuidRepresentation=STANDARD&replicaSet=rs0
