apiVersion: v1
kind: Service
metadata:
  name: timeline-user
  labels:
    app: tinyx
    component: timeline-user
spec:
  selector:
    app: tinyx
    component: timeline-user
  ports:
    - name: http
      port: 8084
      targetPort: 8084
