apiVersion: v1
kind: Secret
metadata:
  name: tinyx-pull-secret
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "registry.cri.epita.fr": {
          "auth": "ajI3dE41UGg5Y3g3MmV5RjNfNnc6ajI3dE41UGg5Y3g3MmV5RjNfNnc="
        }
      }
    }
