apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: shared-neo4j
  labels:
    app: tinyx
    component: neo4j-shared
spec:
  serviceName: shared-neo4j
  replicas: 1
  selector:
    matchLabels:
      app: tinyx
      component: neo4j-shared
  template:
    metadata:
      labels:
        app: tinyx
        component: neo4j-shared
    spec:
      containers:
      - name: neo4j
        image: neo4j:5.9.0
        ports:
        - containerPort: 7474
          name: browser
        - containerPort: 7687
          name: bolt
        env:
        - name: NEO4J_AUTH
          valueFrom:
            secretKeyRef:
              name: neo4j-shared-credentials
              key: NEO4J_AUTH
        - name: NEO4J_ACCEPT_LICENSE_AGREEMENT
          value: "yes"
        volumeMounts:
        - name: neo4j-data
          mountPath: /data
        - name: neo4j-logs
          mountPath: /logs

  volumeClaimTemplates:
  - metadata:
      name: neo4j-data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1Gi
  - metadata:
      name: neo4j-logs
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 500Mi 