apiVersion: v1
kind: Service
metadata:
  name: srvc-search
  labels:
    app: tinyx
    component: srvc-search
spec:
  selector:
    app: tinyx
    component: srvc-search
  ports:
    - name: http
      port: 8085
      targetPort: 8085