kind: Service
apiVersion: v1
metadata:
  name: repo-post
  labels:
    app: tinyx
    component: repo-post
spec:
  selector:
    app: tinyx
    component: repo-post
  ports:
    - name: http
      port: 8082
      targetPort: 8082
      protocol: TCP