apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tinyx

resources:
  - namespace.yml
  - ./mongodb-shared
  - ./neo4j-shared
  - ./srvc-user
  - ./srvc-search
  - ./redis
  - ./repo-post
  - ./repo-social
  - ./elasticsearch
  - ./srvc-home-timeline
  - ./srvc-user-timeline
  - ./ingress.yml
