apiVersion: v1
kind: Service
metadata:
  name: repo-social
  namespace: tinyx
  labels:
    app: tinyx
    component: repo-social
spec:
  selector:
    app: tinyx
    component: repo-social
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083