apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - statefulset.yml
  - service.yml
  - secrets.yml

labels:
  - pairs:
      app: tinyx
      component: mongodb-shared

configMapGenerator:
  - name: mongodb-shared-init-scripts
    files:
      - init.js=init.js
    options:
      disableNameSuffixHash: true 