apiVersion: v1
kind: Secret
metadata:
  name: mongodb-shared-credentials
  labels:
    app: tinyx
    component: mongodb-shared
type: Opaque
stringData:
  MONGO_INITDB_ROOT_USERNAME: "admin"
  MONGO_INITDB_ROOT_PASSWORD: "admin" 