apiVersion: v1
kind: Service
metadata:
  name: shared-mongodb
  labels:
    app: tinyx
    component: mongodb-shared
spec:
  clusterIP: None
  selector:
    app: tinyx
    component: mongodb-shared
  ports:
    - port: 27017
      targetPort: 27017
      name: mongodb 